// Builds src/lib/sites/deltaforce/messages.ts from the redeem pages' own language files,
// so results are recognised whatever language the page is shown in.
// Run with `node scripts/gen-df-messages.ts` when the pages change.
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const LANGUAGE_FILES = [
  'https://redeem.df.garena.sg/cdkgarena/js/glanguage.js',
  'https://www.playdeltaforce.com/cdkredeem/js/glanguage.js',
];

// Message keys the pages show for each outcome (from their response code tables)
const KEYS: Record<string, string[]> = {
  success: ['lang5'],
  invalid: ['lang12', 'error_hint_400073', 'error_hint_400069'],
  used: [
    'lang1',
    'error_hint_400067',
    'error_hint_400068',
    'error_hint_400072',
    'error_hint_51104',
  ],
  expired: ['error_hint_400070'],
};

const messages: Record<string, Set<string>> = Object.fromEntries(
  Object.keys(KEYS).map((status) => [status, new Set<string>()]),
);

for (const url of LANGUAGE_FILES) {
  const source = await (await fetch(url)).text();
  const languages = new Function(`${source};return GLanguage;`)() as Record<
    string,
    Record<string, string>
  >;
  for (const [status, keys] of Object.entries(KEYS)) {
    for (const strings of Object.values(languages)) {
      for (const key of keys) {
        const text = strings?.[key]?.trim();
        if (text) messages[status]?.add(text);
      }
    }
  }
}

const body = Object.entries(messages)
  .map(
    ([status, set]) =>
      `  ${status}: ${JSON.stringify([...set].sort(), null, 4).replace(/\n/g, '\n  ')},`,
  )
  .join('\n');
const out = `// Generated by scripts/gen-df-messages.ts from the redeem pages' language files. Do not edit.
export const DF_MESSAGES: Record<'success' | 'invalid' | 'used' | 'expired', string[]> = {
${body}
};
`;
await writeFile(resolve(import.meta.dirname, '../src/lib/sites/deltaforce/messages.ts'), out);
console.log(
  Object.entries(messages)
    .map(([s, set]) => `${s}: ${set.size}`)
    .join(', '),
);
